// File: ga.v
// Generated by MyHDL 1.0dev
// Date: Mon Oct 10 23:52:59 2016


`timescale 1ns/10ps

module ga (
    a,
    b,
    and_,
    nand_,
    or_,
    nor_
);


input a;
input b;
output and_;
wire and_;
output nand_;
wire nand_;
output or_;
wire or_;
output nor_;
wire nor_;







assign and_ = (b & a);
assign nand_ = (~(b & a));
assign or_ = (b | a);
assign nor_ = (~(b | a));

endmodule
