// File: gates.v
// Generated by MyHDL 1.0dev
// Date: Tue Oct 11 00:24:45 2016


`timescale 1ns/10ps

module gates (
    a,
    b,
    and_,
    nand_,
    or_,
    nor_,
    xor_,
    xnor_
);


input a;
input b;
output and_;
wire and_;
output nand_;
wire nand_;
output or_;
wire or_;
output nor_;
wire nor_;
output xor_;
wire xor_;
output xnor_;
wire xnor_;







assign and_ = (b & a);
assign nand_ = (~(b & a));
assign or_ = (b | a);
assign nor_ = (~(b | a));
assign xor_ = (b ^ a);
assign xnor_ = (~(b ^ a));

endmodule
